# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf35d477005c49de39938d7d9f959c3d9f0cf62a433895481c2f17701b78a35a54c3d2f0689f35191b29d68d340f1b51f91712bc76f8d7e36b27959a233e4761

test:
  secret_key_base: 7758dd833df752119043d235e335636d94ba340d87ec6f7a3b05a1dfaf23402bb8d6865a6404098b115dc6fa5c9097355adeb8cd0fec6fc55f2ea6fb12e75050

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
